### ISSUE TITLE
Spoilers don't unspoiler on click when searching a specific thread

### ISSUE THREAD

**Issue by Wevah** [elektronaut/sugar#105]
Spoilers in the search results page behave correctly when searching all posts, but not when searching a specific thread. Reproducible in both Safari and Firefox.

**Comment by Wevah** [comment]
Affects posts on user pages, too.

**Comment by elektronaut** [comment]
Thanks, fixed in 15cabc0.

**Comment by Wevah** [comment]
A missing comma was the issue? D'oh!

Thanks!
