### ISSUE TITLE
NSFW posts should be filtered from user profiles

### ISSUE THREAD

**Issue by elektronaut** [elektronaut/sugar#65]

**Comment by Wevah** [comment]
They should be filtered/spoilered from search results, too (possibly with opt-out).

**Comment by elektronaut** [comment]
Yeah, that's a good point.

**Comment by Wevah** [comment]
I've got code for this; just need a good message and style.

**Comment by Wevah** [comment]
It's not 100% perfect, but it should help keep people from getting into trouble at work! 🤓

**Comment by elektronaut** [comment]
Excellent work @Wevah. My laptop is currently dead, but I'll deploy it when I can.
