### ISSUE TITLE
LoadError: cannot load such file -- tasks/emoji.rake

### ISSUE THREAD

**Issue by qojop** [elektronaut/sugar#88]
![](http://i.imgur.com/GnS1tml.png)

```
vagrant@sugar-dev-box:/vagrant/sugar$ rake db:create --trace
rake aborted!
LoadError: cannot load such file -- tasks/emoji.rake
/vagrant/sugar/rakefile:5:in `load'
/vagrant/sugar/rakefile:5:in `<top (required)>'
/usr/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load'
/usr/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load_rakefile'
/usr/lib/ruby/2.2.0/rake/application.rb:689:in `raw_load_rakefile'
/usr/lib/ruby/2.2.0/rake/application.rb:94:in `block in load_rakefile'
/usr/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/2.2.0/rake/application.rb:93:in `load_rakefile'
/usr/lib/ruby/2.2.0/rake/application.rb:77:in `block in run'
/usr/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/usr/bin/rake:33:in `<main>'
vagrant@sugar-dev-box:/vagrant/sugar$
```

How to fix?

**Comment by qojop** [comment]
Another Error:
```
Bundle complete! 61 Gemfile dependencies, 166 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
vagrant@sugar-dev-box:/vagrant/sugar$ rake db:create
Could not find b3s_emoticons-0.0.1 in any of the sources
Run `bundle install` to install missing gems.
```

**Comment by elektronaut** [comment]
Thanks for the report, I will look into it.

**Comment by mavu** [comment]
The "Could not find b3s_emoticons-0.0.1 in any of the sources" error seems to go away if you remove your TODO: from description and summary in b3s_emoticons.gemspec in the b3s_emoticons gem.

Possibly a newer rubygems version that is more strict?

The first error is because there is this line in the main Rakefile:
load 'tasks/emoji.rake'

If i remove it i can start rake tasks.
Is it possible thats a remnant of splitting stuff out into the b3s_emoticons gem? (just guessing here)

**Comment by elektronaut** [comment]
Perhaps. I haven't seen it in either production or on Travis CI, but I'm able to reproduce it with Vagrant.

I've updated b3s_emoticons with a proper description, that seems to fix that issue.

As for the Rake error, make sure you're using the bundled `bin/rake` and not just `rake`

Thanks for the helpful debugging, please report back if you're still having trouble.

**Comment by poombavai** [comment]
Hello..
Getting the same error. How to solve this?

**Comment by elektronaut** [comment]
Does it work if you try starting solr with `bin/sunspot-solr start`?

**Comment by poombavai** [comment]
No. Getting same error.

**Comment by elektronaut** [comment]
Actually, there's no need for that line in the Rakefile. I've removed it.
