### ISSUE TITLE
Error when creating a new discussion

### ISSUE THREAD

**Issue by sallymacnicholas** [elektronaut/sugar#96]
Hi there! I'm trying to get up and running with your sugar repo. I have it all set up on a VM, and am able to login on localhost:3000. However, when I go to create a new discussion I am receiving this error: 
`Connection refused - {:data=>"<?xml version=\"1.0\" encoding=\"UTF-8\"?><add><doc><field name=\"id\">Discussion 5</field><field name=\"type\">Discussion</field><field name=\"type\">Exchange</field><field name=\"type\">ActiveRecord::Base</field><field name=\"class_name\">Discussion</field><field name=\"type_s\">Discussion</field><field name=\"poster_id_i\">1</field><field name=\"last_poster_id_i\">1</field><field name=\"trusted_b\">true</field><field name=\"closed_b\">false</field><field name=\"sticky_b\">false</field><field name=\"created_at_d\">2016-09-12T01:12:17Z</field><field name=\"updated_at_d\">2016-09-12T01:12:17Z</field><field name=\"last_post_at_d\">2016-09-12T01:12:17Z</field><field name=\"title_text\">please work</field></doc></add>", :headers=>{"Content-Type"=>"text/xml"}, :method=>:post, :params=>{:wt=>:ruby}, :query=>"wt=ruby", :path=>"update", :uri=>#<URI::HTTP http://localhost:8982/solr/development/update?wt=ruby>, :open_timeout=>nil, :read_timeout=>nil, :retry_503=>nil, :retry_after_limit=>nil}`

So I switched the port to 3000 in the sunspot.yml file because it was at 8981, but then I got this error: Net:::ReadTimeout

**Comment by elektronaut** [comment]
Hi! Yeah, that is definitively an issue with Sunspot connectivity. 

8983 should be the right port, though. Solr runs as a separate process in the background, pointing the Rails process at itself won't work.

Can you verify that the Solr process is running? There should be a `sunspot-solr.pid` file pointing to it, and `curl http://localhost:8983/solr/` should return a HTTP response.

**Comment by sallymacnicholas** [comment]
It looks like the Solr process is not running. It is creating the sunspot-solr.pid file but when I curl the response I get is : 
```<h2>SolrCore Initialization Failures</h2>
          <ul></ul>
          <p>Please check your logs for more information</p>```
I don't see any logs though, so not sure what to do from here. I set up everything exactly the way it states in the readme. Any ideas?

**Comment by Wevah** [comment]
Do any of the rece t solr-related commits help with this?
