### ISSUE TITLE
User status expansion

### ISSUE THREAD

**Issue by Down10** [elektronaut/sugar#97]
Currently, user accounts are visible in one of two states which, as I understand it, is flagged as an attribute:

* Active
   * User is registered, can login, and has posted with a recent time period.
* Banned
   * User is registered, cannot login, and has posted but has been deliberately barred from posting/editing.
   * **OR** This user has registered, has made zero or more posts, and may or may not have been actively barred from posting or editing.

I find this to be a limitation of the software and confusing to forum participants as to the true nature of a banned user, whether they willfully stopped posting on their own or had to be forcefully removed because of bad behavior.

I propose instead that user accounts be instead in one of the following 5 states:

* Reserved
   * User is unregistered, but the account is set aside for internal use or special cases. These would be accounts set aside as "invites," or for VIPs (Kanye wants an account).
* Inactive
   * This user is registered, can login, but has made zero posts or has not posted within a specified time period. This will be the default state of all registered users if they do not regularly post and participate on the forum.
* Active
   * User is registered, can login, and makes posts regularly.
* Suspended (or Self-Banned)
   * User is registered, cannot login until a specified time period has passed, has made zero or more posts, but has not been banned outright. Active users can file a request to be suspended by a single admin (aka self-ban). Likewise, suspended users can file a request to be active once again.
* Banned
   * User is registered, cannot login, and cannot file a request to be active again. Bans can be lifted, but only by one or more admins.
* Deceased
   * User has been confirmed as passed away. Will not be returning, and will not be active again.

This is just one method. I'm sure other methods of designating users exist that are more robust, but I think these features would be a great improvement to the forum.

edit: Added "Deceased" to list. :(

**Comment by elektronaut** [comment]
Good points. The lack of nuance when it comes to banned users has been annoying me too.

I don't think we need a Reserved type. Seems like a lot of work for something that won't see much use, I'd rather keep the complexity down.

Differentiating Suspended and Banned would be great. I also think self-banning should be a separate thing, maybe call it something like Hiatus. 

I'm a bit vary of completely automating the process. If we do, probably need to flag some users as protected. Sometimes people need a break or life gets in the way, and that's OK. I'd hate to put up extra barriers for, say, a disabled user to get in once in a while to make a post.
